# runs-on: emu

services:
  web:
    container_name: mixed-web
    image: nginx:1.29
    restart: unless-stopped

  backup:
    container_name: mixed-backup
    image: alpine:3.22
    restart: no

  migrate:
    container_name: mixed-migrate
    image: alpine:3.22
